### ISSUE TITLE
Context getting lost

### ISSUE THREAD

**Issue by rkreienbuehl** [alfateam/node-cls#2]
I run a server with koajs and mongoose and implemented `node-cls` for accessing context data inside mongoose-middleware.
When experimenting with `node-cls`, I encountered a bug:

Therefore I built a small koa-middleware:
``` ts
export async function zoneMiddleware(ctx: Context, next) {
  const name =
    ctx.req.socket.remoteFamily +
    '|' +
    ctx.req.socket.remoteAddress +
    '|' +
    ctx.req.socket.remotePort;

  const context = cls.create('request-context');
  context.name = name;

  await context.start();
  console.log(cls.get('request-context').name);
  await next();
  cls.exit('request-context');
}
```

And the mongoose-middleware:
``` ts
schema.pre(
    'save',
    async function (this: any, next: mongoose.HookNextFunction) {
      console.log(getType(this) + ': pre save');

      console.log(cls.get('request-context').name);
      next();
    }
  );
```

The request-method then creates a new mongoose-document and saves it. This works as expected, but when I change the document and save it again, the context is lost:
```ts
async get() {
    console.log(cls.get('request-context').name);

    const kitty = new Kitten({ name: 'kitty' });
    await kitty.save();

    kitty.name = 'new Kitty';
    kitty.test.test2.push('test');
    kitty.test.test3.push('test2');
    await kitty.save();

    return { data: {} };
  }
```

On a request I get the following log:
``` sh
IPv6|::1|52799
IPv6|::1|52799
document: pre save
IPv6|::1|52799
document: pre save

  TypeError: Cannot read property 'name' of undefined
```

**Comment by rkreienbuehl** [comment]
Ok, after rereading the whole README and checking my code, I realized, that the import of `node-cls` was not the first in my app, because the middleware was in a separate file. After setting the imports in the first line, everything worked.

**Comment by lroal** [comment]
Great !
